set database transaction control mvlocks;

create domain UserId as varchar(64);

create domain AuctionId as bigint;
create domain BidId as bigint;

create domain MonetaryAmount as numeric(18, 6);
create domain Currency as varchar(3);


create table AUCTION
(
    ID             AuctionId generated always as identity (start with 1) not null primary key,
    RULES          varchar(64)                                           not null,
    SELLER         UserId                                                not null,
    DESCRIPTION    varchar(256)                                          not null,
    RESERVE        MonetaryAmount                                        not null,
    CURRENCY       Currency                                              not null,
    COMMISSION     numeric(4, 4)                                         not null,
    CHARGE_PER_BID MonetaryAmount                                        not null,
    STATE          varchar(8) default 'open'                             not null,

    check (STATE in ('open', 'closed', 'settling', 'settled'))
);

CREATE INDEX AUCTION_STATE ON AUCTION(STATE);

create table AUCTION_WINNER
(
    AUCTION AuctionId not null primary key foreign key references AUCTION(ID),
    WINNER  UserId    not null,
    OWED    MonetaryAmount
);

create sequence BID_ORDER as bigint start with 1 no cycle;

create table BID
(
    -- should be generated always as identity, but Spring Data JDBC sends a null ID
    -- which violates the constraint!
    ID      BidId generated by default as identity (start with 1) not null primary key,

    AUCTION AuctionId                                             not null references AUCTION,
    BIDDER  UserId                                                not null,
    AMOUNT  MonetaryAmount                                        not null
);

create index BID_AUCTION on BID(AUCTION);
create index BID_AMOUNT on BID(AMOUNT);

